name: godarna
description: منصة مغربية لتأجير العقارات شبيهة بـ Airbnb
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Supabase
  supabase_flutter: ^2.5.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.2
  image_picker: ^1.0.8
  image_cropper: ^9.1.0
  
  # Navigation
  go_router: ^16.1.0
  
  # Localization
  flutter_gen_runner: ^5.4.0
  intl: ^0.19.0
  
  # Utils
  shared_preferences: ^2.3.2
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  
  # Maps
  google_maps_flutter: ^2.6.0
  
  # Date & Time
  intl: ^0.19.0
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.7.0
  
  # Validation
  form_validator: ^2.1.2
  
  # UI Enhancements
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.1
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700