name: godarna
description: GoDarna – Moroccan rentals platform (Airbnb-like) with OTP auth, COD payment, Supabase backend, and bilingual UI.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.3
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  easy_localization: ^3.0.5
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - .env